### ISSUE TITLE
[BUG] - no application found to open the file after extraction

### ISSUE THREAD

**Issue by avichou** [YourKalamity/lazy-dsi-file-downloader#18] opened 2022-01-27 18:18 UTC
impossbile to open it,no application found

downdload and extract on macOS,i can only read it usuing textedit but that is useless

should launch the app 

macOS 12.2 m1

**Comment by YourKalamity** [comment] 2022-02-08 09:20
Try launching it with the Terminal app

**Comment by YourKalamity** [comment] 2022-05-04 09:15
I believe this is caused by the `.` in the filename, should be fixed with 8db85d365a66dd53c3dcb1b5129b6b5d8419eda8

**Closed by YourKalamity** 2022-05-04 09:15 UTC
Labels: bug
